### ISSUE TITLE
[xDD] Hits value incorrect on v2 api

### ISSUE THREAD

**Issue by dvince2** [DARPA-ASKEM/TA1-TA4-Tickets#4]
Currently, ES is returning a fuzzy hits value which doesn't work well with the facets results which is exact:

![image](https://github.com/DARPA-ASKEM/TA1-TA4-Tickets/assets/30270901/92e7dcda-1320-4581-b56d-7c5a86062fb2)

In this case here, we'd display `18425/10000`. We need to have `hits.value` return the true number of hits, or the true number of hits be available somewhere on the return value.

**Comment by iross** [comment]
Fix deployed!

**Comment by dvince2** [comment]
Confirmed fixed
